### ISSUE TITLE
Deployment of RC5 failed for Scala 2.11

### ISSUE THREAD

**Issue by schmitch** [scala/scala-java8-compat#79]
Actually the following directory is empty on Maven Central:
http://central.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.11/0.8.0-RC5/

So actually some files are missing here. What's suspicious is that there is one file `scala-java8-compat_2.11-0.8.0-RC5.pom.asc`

**Comment by SethTisue** [comment]
when we tried to promote https://oss.sonatype.org/content/repositories/orgscala-lang-1335/ . it's not clear why 1335 didn't work but 1336 (with the 2.12.0-RC1 artifact did); "i did the same thing for both" said @adriaanm. @szeiger hypothesized "Maybe it's still building? Travis is configured to build on 2.11.8, 2.12.0-M5 and 2.12.0-RC1... The build logs are here: https://travis-ci.org/scala/scala-java8-compat/builds/158760426 - According to these everything went well and all artifacts were published to the staging repo."

the error log for 1335 says `Missing Signature: '/org/scala-lang/modules/scala-java8-compat_2.11/0.8.0-RC5/scala-java8-compat_2.11-0.8.0-RC5.pom.asc' does not exist for 'scala-java8-compat_2.11-0.8.0-RC5.pom'.`

rather than launch a full investigation, tempted to just tag 0.8.0-RC6 without any code changes and just try again, making absolutely sure Travis is completely finished before doing anything over on Sonatype.

**Comment by schmitch** [comment]
actually the error log is really strange since the signature was actually uploaded?

**Comment by szeiger** [comment]
Yes, I agree. I've retagged as RC6: https://github.com/scala/scala-java8-compat/releases/tag/v0.8.0-RC6.  Build is running: https://travis-ci.org/scala/scala-java8-compat/builds/159293774

**Comment by SethTisue** [comment]
I went on oss.sonatype.org and closed & released the staging repo (1338) that had the artifacts for 2.12.0-RC1, but there was just the one staging repo, not the three I expected. I don't see any clues in the Travis logs. :-(

**Comment by schmitch** [comment]
Since local builds are working, can't you just copy the Builds from a local machine with the gpg key to oss.sonatype?

**Comment by SethTisue** [comment]
I guess, but we publish a lot of different stuff using this same infrastructure, so we reallllly want it to work and not have to do manual steps all the time.

**Comment by SethTisue** [comment]
hmm, perhaps the `admin/build.sh` in this repo is antiquated. it's an Achilles heel of this stuff that each repo has its own `admin/build.sh`

**Comment by SethTisue** [comment]
ohhhhh, new theory! I went and looked in the old broken staging repo (1335) and it has RC6 artifacts in it! so I think we need to get rid of that repo entirely (we'd left it around in case there were more clues in there we hadn't seen yet), then try again. I will do that.

**Comment by SethTisue** [comment]
ok, so two staging repos not three, but one of them has both the _2.11 and the _2.12.0-RC1 artifacts, so yay. closed, released. hopefully the artifacts will show up on central soon

**Comment by SethTisue** [comment]
🎉

**Comment by SethTisue** [comment]
also, TIL that e.g. https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12.0-RC1/0.8.0-RC7/ can 404 even though https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12.0-RC1/0.8.0-RC7/scala-java8-compat_2.12.0-RC1-0.8.0-RC7.jar can be retrieved, so never use directory listings to confirm whether something has made it to Maven Central yet

**Comment by schmitch** [comment]
eh yeah I basically didn't did that. I actually added it to my project ;)
But the directory listing mostly works if you wait > 1 days. As you can see here: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12.0-RC1/0.8.0-RC7/
However everything is good now, finally I can try everything new out +1
